### ISSUE TITLE
Crash with newest Electroblob's Wizardry

### ISSUE THREAD

**Issue by ElReptil** [Coders-After-Dark/CompatSkills#119]
It appears the newest version of Electroblob's Wizardry, which is known to break addons, also broke this mod's wizardry integration (which I didn't know existed, TIL). 

Trying to do anything in an arcane workbench with the newest version gets this crash:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-11-08 23:33:13 CET
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: electroblob/wizardry/tileentity/ContainerArcaneWorkbench
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: electroblob/wizardry/tileentity/ContainerArcaneWorkbench
    at codersafterdark.compatskills.common.compats.electroblob.WizardyEventHandler.onSpellBind(WizardyEventHandler.java:21)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1337_WizardyEventHandler_onSpellBind_SpellBindEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at electroblob.wizardry.inventory.ContainerArcaneWorkbench.onApplyButtonPressed(ContainerArcaneWorkbench.java:435)
    at electroblob.wizardry.packet.PacketControlInput.lambda$onMessage$2(PacketControlInput.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5465017864 bytes (5211 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -Xmx10G -Xms10G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F6_pre1 120 mods loaded, 120 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                         | Version                   | Source                                             | Signature                                |
       |:------ |:-------------------------- |:------------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                  | 1.12.2                    | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                        | 9.42                      | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                        | 8.0.99.99                 | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                      | 14.23.5.2854              | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ivtoolkit                  | 1.3.3-1.12                | minecraft.jar                                      | None                                     |
       | LCHIJA | xaerominimap_core          | 1.12.2-1.0                | minecraft.jar                                      | None                                     |
       | LCHIJA | xaeroworldmap_core         | 1.12.2-1.0                | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore                | 7.7.4                     | minecraft.jar                                      | None                                     |
       | LCHIJA | bspkrscore                 | 7.6.0.1                   | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
       | LCHIJA | armorstatushud             | 1.43.0                    | [1.12]ArmorStatusHUD-client-1.43.0.jar             | None                                     |
       | LCHIJA | movillages                 | 1.5.4                     | [1.12]MoVillages-1.5.4.jar                         | None                                     |
       | LCHIJA | statuseffecthud            | 1.43.0                    | [1.12]StatusEffectHUD-client-1.43.0.jar            | None                                     |
       | LCHIJA | ambientenvironment         | 1.0.1                     | AmbientEnvironment-1.0.2.jar                       | None                                     |
       | LCHIJA | crafttweaker               | 4.1.20                    | CraftTweaker2-1.12-4.1.20.594.jar                  | None                                     |
       | LCHIJA | armoreablemobs             | 1.1.2                     | armoreablemobs-1.12.2-1.1.8.jar                    | None                                     |
       | LCHIJA | attributefix               | 1.0.4                     | AttributeFix-1.12.2-1.0.4.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | baubles                    | 1.5.2                     | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | atum                       | 2.0.19                    | Atum-1.12.2-2.0.19.jar                             | None                                     |
       | LCHIJA | jei                        | 4.16.1.302                | jei_1.12.2-4.16.1.302.jar                          | None                                     |
       | LCHIJA | quark                      | r1.6-179                  | Quark-r1.6-179.jar                                 | None                                     |
       | LCHIJA | autoreglib                 | 1.3-32                    | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHIJA | baubleshud                 | 5.0.2                     | BaublesHud-1.12.2-5.0.2.jar                        | None                                     |
       | LCHIJA | bettercaves                | 1.12.2                    | bettercaves-1.12.2-2.0.4.jar                       | None                                     |
       | LCHIJA | bettercombatmod            | 1.5.6                     | BetterCombat-1.12.2-1.5.6.jar                      | None                                     |
       | LCHIJA | bettermineshafts           | 1.12.2-2.1.1              | BetterMineshaftsForge-1.12.2-2.1.1.jar             | None                                     |
       | LCHIJA | llibrary                   | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs                | 1.5.8                     | mowziesmobs-1.5.8.jar                              | None                                     |
       | LCHIJA | patchouli                  | 1.0-21                    | Patchouli-1.0-21.jar                               | None                                     |
       | LCHIJA | toughasnails               | 3.1.0.139                 | ToughAsNails-1.12.2-3.1.0.139-universal.jar        | None                                     |
       | LCHIJA | bewitchment                | 0.22.43                   | bewitchment-1.12.2-0.0.22.43.jar                   | None                                     |
       | LCHIJA | biomesoplenty              | 7.0.1.2444                | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
       | LCHIJA | bloodmoon                  | 1.5.3                     | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | bookshelf                  | 2.3.590                   | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | forgelin                   | 1.8.4                     | Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | bountiful                  | 2.2.2                     | Bountiful-2.2.2.jar                                | None                                     |
       | LCHIJA | charm                      | 1.12.2-1.3.7              | Charm-1.12.2-1.3.7.jar                             | None                                     |
       | LCHIJA | climaticbiomesjbg          | 2.15.8                    | ClimaticBiomes-2.15.8-MC1.12.2.jar                 | None                                     |
       | LCHIJA | colytra                    | 1.2.0.4                   | colytra-1.12.2-1.2.0.4.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | combustfish                | 1.0.3.4                   | combustfish-1.12.2-1.0.3.4.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | comforts                   | 1.4.1.2                   | comforts-1.12.2-1.4.1.2.jar                        | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | reskillable                | 1.12.2-1.13.0             | Reskillable-1.12.2-1.13.0.jar                      | None                                     |
       | LCHIJA | compatskills               | 1.12.2-1.17.0             | CompatSkills-1.12.2-1.17.0.jar                     | None                                     |
       | LCHIJA | craftstudioapi             | 1.0.0                     | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | ctgui                      | 1.0.0                     | CraftTweaker2-1.12-4.1.20.594.jar                  | None                                     |
       | LCHIJA | crafttweakerjei            | 2.0.3                     | CraftTweaker2-1.12-4.1.20.594.jar                  | None                                     |
       | LCHIJA | defaultworldgenerator-port | 1.12-2.3                  | DefaultWorldGenerator-port-1.12-2.3.jar            | None                                     |
       | LCHIJA | defiledlands               | 1.4.3                     | defiledlands-1.12.2-1.4.3.jar                      | None                                     |
       | LCHIJA | dymm                       | 2.0.2                     | DocumentYourModMod-2.0.2.jar                       | None                                     |
       | LCHIJA | sereneseasons              | 1.2.18                    | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
       | LCHIJA | orelib                     | 3.6.0.1                   | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                  | 3.6.2.1                   | DynamicSurroundings-1.12.2-3.6.2.1.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | ebwizardry                 | 4.3.1                     | ElectroblobsWizardry-4.3.1-MC1.12.2.jar            | None                                     |
       | LCHIJA | enchdesc                   | 1.1.20                    | EnchantmentDescriptions-1.12.2-1.1.20.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | erebus                     | 1.0.31                    | Erebus-1.0.31.jar                                  | None                                     |
       | LCHIJA | lieutenant                 | 1.4                       | lieutenant-1.12.jar                                | None                                     |
       | LCHIJA | extratan                   | 5.2.587                   | extra-tan-5.2.591.jar                              | None                                     |
       | LCHIJA | potioncore                 | 1.9_for_1.12.2            | PotionCore-1.9_for_1.12.2.jar                      | None                                     |
       | LCHIJA | extra_spells               | 1.2.0                     | ExtraSpells-1.12.2-1.2.0.jar                       | None                                     |
       | LCHIJA | familiarfauna              | 1.0.11                    | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
       | LCHIJA | fastfurnace                | 1.3.1                     | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LCHIJA | mod_lavacow                | 1.2.2                     | Fish's+Undead+Rising-1.2.2.jar                     | None                                     |
       | LCHIJA | foamfix                    | 0.10.10-1.12.2            | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCHIJA | cfm                        | 6.3.1                     | furniture-6.3.1-1.12.2.jar                         | None                                     |
       | LCHIJA | futuremc                   | 0.2.4.1                   | future-mc-1.12.2-0.2.4.1.jar                       | None                                     |
       | LCHIJA | galaxite                   | 1.1.2                     | galaxite-1.1.2-mc1.12.x.jar                        | None                                     |
       | LCHIJA | getexpforeverything        | 1.12.2                    | getexpforeverything-1.12.2.jar                     | None                                     |
       | LCHIJA | ghostspells                | 0.7-alpha                 | Ghostspells-0.7-alpha.jar                          | None                                     |
       | LCHIJA | grimoireofgaia             | 1.7.2                     | GrimoireOfGaia3-1.12.2-1.7.2.jar                   | None                                     |
       | LCHIJA | horsestandstill            | 1.12.2-0.0.1              | horsestandstill-1.12.2-0.0.1.jar                   | None                                     |
       | LCHIJA | iceandfire                 | 1.9.1                     | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
       | LCHIJA | improvedbackpacks          | 1.12.2-1.5.0.0            | ImprovedBackpacks-1.12.2-1.5.0.0.jar               | None                                     |
       | LCHIJA | incontrol                  | 3.9.18                    | incontrol-1.12-3.9.18.jar                          | None                                     |
       | LCHIJA | mantle                     | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | inspirations               | 1.12.2-0.2.9              | Inspirations-1.12.2-0.2.9.jar                      | None                                     |
       | LCHIJA | itemscroller               | 0.12.0                    | itemscroller-1.12.2-0.12.0.jar                     | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | jepb                       | 1.2.1                     | jepb-1.12-1.2.1.jar                                | None                                     |
       | LCHIJA | jetif                      | 1.5.2                     | jetif-1.12.2-1.5.2.jar                             | None                                     |
       | LCHIJA | jaff                       | 1.7_for_1.12              | JustAFewFish-1.7_for_1.12.jar                      | None                                     |
       | LCHIJA | loottweaker                | 0.2.0                     | LootTweaker-0.2.0+MC1.12.2.jar                     | None                                     |
       | LCHIJA | jeresources                | 0.9.2.60                  | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHIJA | livingenchantment          | 3.2.3                     | living_enchantment-3.2.3.jar                       | None                                     |
       | LCHIJA | magma_monsters             | 0.3.0                     | MagmaMonsters-0.3.0.jar                            | None                                     |
       | LCHIJA | materialchanger            | 1.0                       | materialchanger1.0.3-1.12.2.jar                    | None                                     |
       | LCHIJA | mcwdoors                   | 1.0                       | mcw-doors-1.0.0-mc1.12.2.jar                       | None                                     |
       | LCHIJA | mia                        | 1.12.2-0.2.0e             | mia-1.12.2-0.2.0e.jar                              | None                                     |
       | LCHIJA | multimob                   | 1.0.5                     | multimob-1.0.5.jar                                 | None                                     |
       | LCHIJA | pillar                     | 1.2-10                    | Pillar-1.2-10.jar                                  | None                                     |
       | LCHIJA | pi                         | 4.0.0                     | Potion+Icon+Remover-1.12-4.0.0.jar                 | None                                     |
       | LCHIJA | primitivemobs              | 1.2.3a                    | primitivemobs-1.2.3a.jar                           | None                                     |
       | LCHIJA | progressivebosses          | 1.5.4                     | ProgressiveBosses-1.5.4-mc1.12.x.jar               | None                                     |
       | LCHIJA | reccomplex                 | 1.4.8.2                   | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | LCHIJA | additionalstructures       | 2.3.1                     | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar   | None                                     |
       | LCHIJA | roguelike                  | 2.1.4                     | RoguelikeDungeonsFnarEdition-1.12.2-2.1.4.jar      | None                                     |
       | LCHIJA | sandbag                    | 1.12.2-1.0.2              | sandbag-1.12.2-1.0.2.jar                           | None                                     |
       | LCHIJA | t3s4ebw                    | 1.0                       | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar       | None                                     |
       | LCHIJA | slideemall                 | 1.03                      | slideemall-1.03.jar                                | None                                     |
       | LCHIJA | spartanweaponry            | beta 1.3.8                | SpartanWeaponry-1.12.2-beta-1.3.8.jar              | None                                     |
       | LCHIJA | spartanfire                | 0.08                      | spartanfire-0.08.jar                               | None                                     |
       | LCHIJA | spartanshields             | 1.5.4                     | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
       | LCHIJA | spawnercontrol             | 1.6.3b                    | SpawnerControl-1.6.3b.jar                          | None                                     |
       | LCHIJA | stg                        | 1.12.2-1.2.3              | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LCHIJA | stygian                    | 1.0.4                     | stygian-1.0.4.jar                                  | None                                     |
       | LCHIJA | tellme                     | 0.7.0-dev.20190610.165828 | tellme-1.12.2-0.7.0-dev.20190610.165828.jar        | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | thesummoner                | 1.0.1-beta                | thesummoner-1.0.1.jar                              | None                                     |
       | LCHIJA | tips                       | 1.0.9                     | Tips-1.12.2-1.0.9.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tombmanygraves             | 1.12-4.2.0                | TombManyGraves-1.12-4.2.0.jar                      | None                                     |
       | LCHIJA | torohud                    | 1.12.2-5                  | torohud-1.12.2-5.jar                               | None                                     |
       | LCHIJA | twilightforest             | 3.11.1020                 | twilightforest-1.12.2-3.11.1020-universal.jar      | None                                     |
       | LCHIJA | uniquee                    | 1.9.0                     | Unique+Enchantments+V1.12.2-1.9.jar                | None                                     |
       | LCHIJA | vanillafix                 | 1.0.10-150                | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCHIJA | villagenames               | 3.3.1                     | VillageNames-1.12.2-3.3.1.jar                      | None                                     |
       | LCHIJA | vulcanite                  | 1.5.2                     | vulcanite-1.5.2-mc1.12.x.jar                       | None                                     |
       | LCHIJA | waystones                  | 4.1.0                     | Waystones_1.12.2-4.1.0.jar                         | None                                     |
       | LCHIJA | wolfarmor                  | 3.7.5                     | wolfarmor-1.12.2-3.7.5-universal-signed.jar        | e94e38a605842477f3ec218e6fcf781f6b3f7f89 |
       | LCHIJA | xaerominimap               | 20.23.0                   | Xaeros_Minimap_20.23.0_Forge_1.12.jar              | None                                     |
       | LCHIJA | xaeroworldmap              | 1.11.0                    | XaerosWorldMap_1.11.0_Forge_1.12.jar               | None                                     |
       | LCHIJA | xpfromharvest              | 1.2.0                     | XPFromHarvest-1.12.2-1.2.0.jar                     | None                                     |
       | LCHIJA | gogredux                   | 1.0.0                     | gogredux-1.12.2-1.0.0.jar                          | None                                     |
       | LCHIJA | phosphor-lighting          | 1.12.2-0.2.7              | phosphor-forge-mc1.12.2-0.2.7-universal.jar        | None                                     |
       | LCHIJA | thebetweenlands            | 3.7.1                     | TheBetweenlands-3.7.1-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
  Loaded coremods (and transformers): SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.43.jar)
                                        
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.11.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.7.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      XaeroMinimapPlugin (Xaeros_Minimap_20.23.0_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.1-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
                                        codersafterdark.reskillable.base.asm.ClassTransformer
                                      FutureMC (future-mc-1.12.2-0.2.4.1.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - ToughAsNailsPlugin (Enabled/Not Forced)
                                     - TwilightForestPlugin (Enabled/Not Forced)
  Patchouli open book context: n/a
  Suspected Mods: CompatSkills (compatskills), Electroblob's Wizardry (ebwizardry)

**Comment by pupnewfster** [comment]
We aren't actively maintaining this anymore (at least not 1.12), so your best bet would be to either use the older version that doesn't break their own API after a lot of devs have moved on from 1.12... Or to in the compatskills config disable our compat with electroblob's wizardry and hope that it then disables it enough it doesn't try to run through any of the code paths that cause it to crash, given it doesn't sound like you are really using it anyways (if memory serves all the integration does is make it so that you can't make wands etc in the table if you don't meet the requirements to use the finished item, or something like that).

**Comment by ElReptil** [comment]
Thanks! Somehow I managed to completely miss the ebwizardry config option. Turning your wizardry compat off seems to resolve the problem, and as you suspect I wasn't using it anyway.

**Comment by TheidenHD** [comment]
I fix it.

**Comment by SomeRandomPetey** [comment]
Can confirm and reproduce.

**Comment by TheidenHD** [comment]
https://github.com/TheidenHD/CompatSkills/releases/latest
